=== TDave555/YIF399_XMLGyak/XMLTaskYIF399/XMLSchemaYIF399.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">

    <!-- típusok-->

    <xs:complexType name="rendezotype">
        <xs:sequence>
            <xs:element name="rendezo" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="eletkor" type="xs:integer"/>
                        <xs:element name="lakhely" type="lakszekhelytype"/>
                    </xs:sequence>
                    <xs:attribute name="RID" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="megjelenestype">
        <xs:sequence>
            <xs:element name="ev" type="xs:integer"/>
            <xs:element name="honap" type="xs:integer"/>
            <xs:element name="nap" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="lakszekhelytype">
        <xs:sequence>
            <xs:element name="orszag" type="xs:string"/>
            <xs:element name="varos" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="szinesztype">
        <xs:sequence>
            <xs:element name="szinesz" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="eletkor" type="xs:integer"/>
                        <xs:element name="lakhely" type="lakszekhelytype"/>
                    </xs:sequence>
                    <xs:attribute name="SzID" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="studiotype">
        <xs:sequence>
            <xs:element name="studio" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nev" type="xs:string"/>
                        <xs:element name="alapitas" type="xs:integer"/>
                        <xs:element name="vezeto" type="xs:string"/>
                        <xs:element name="szekhely" type="lakszekhelytype"/>
                    </xs:sequence>
                    <xs:attribute name="SID" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="forgatokonyvtype">
        <xs:sequence>
            <xs:element name="forgatokonyv" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="oldalszam" type="xs:positiveInteger"/>
                        <xs:element name="formatum">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="nyomtatott" />
                                    <xs:enumeration value="digitális" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="peldanyszam" type="xs:positiveInteger"/>
                    </xs:sequence>
                    <xs:attribute name="FkID" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="filmtype">
        <xs:sequence>
            <xs:element name="film" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="cim" type="xs:string"/>
                        <xs:element name="bevetel" type="xs:long"/>
                        <xs:element name="hossz" type="xs:integer"/>
                        <xs:element name="mufaj" type="xs:string"/>
                        <xs:element name="megjelenes" type="megjelenestype"/>
                        <xs:element name="RID">
                            <xs:complexType>
                                <xs:attribute name="refID" type="xs:IDREF"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="SID">
                            <xs:complexType>
                                <xs:attribute name="refID" type="xs:IDREF"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="FkID">
                            <xs:complexType>
                                <xs:attribute name="refID" type="xs:IDREF"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="FID" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="szereplestype">
        <xs:sequence>
            <xs:element name="szereples" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="FID">
                            <xs:complexType>
                                <xs:attribute name="refID" type="xs:IDREF"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="SzID">
                            <xs:complexType>
                                <xs:attribute name="refID" type="xs:IDREF"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="szerep" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <!-- root element-->
    
    <xs:element name="filmtar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rendezok" type="rendezotype" maxOccurs="1"/>
                <xs:element name="szineszek" type="szinesztype" maxOccurs="1"/>
                <xs:element name="studiok" type="studiotype" maxOccurs="1"/>
                <xs:element name="forgatokonyvek" type="forgatokonyvtype" maxOccurs="1"/>
                <xs:element name="filmek" type="filmtype" maxOccurs="1"/>
                <xs:element name="szereplesek" type="szereplestype" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>

        <!-- kulcsok-->
        <xs:key name="RID">
            <xs:selector xpath="rendezo"/>
            <xs:field xpath="@RID"/>
        </xs:key>
        <xs:key name="SzID">
            <xs:selector xpath="szinesz"/>
            <xs:field xpath="@SzID"/>
        </xs:key>
        <xs:key name="SID">
            <xs:selector xpath="studio"/>
            <xs:field xpath="@SID"/>
        </xs:key>
        <xs:unique name="FkID">
            <xs:selector xpath="forgatokonyv"/>
            <xs:field xpath="@FkID"/>
        </xs:unique>
        <xs:key name="FID">
            <xs:selector xpath="film"/>
            <xs:field xpath="@FID"/>
        </xs:key>
        <xs:keyref name="refRID" refer="RID">
            <xs:selector xpath="film/RID"/>
            <xs:field xpath="@refID"/>
        </xs:keyref>
        <xs:keyref name="refSID" refer="SID">
            <xs:selector xpath="film/SID"/>
            <xs:field xpath="@refID"/>
        </xs:keyref>
        <xs:keyref name="refFkID" refer="FkID">
            <xs:selector xpath="film/FkID"/>
            <xs:field xpath="@refID"/>
        </xs:keyref>
        <xs:keyref name="refFID" refer="FID">
            <xs:selector xpath="szereples/FID"/>
            <xs:field xpath="@refID"/>
        </xs:keyref>
        <xs:keyref name="refSzID" refer="SzID">
            <xs:selector xpath="szereples/SzID"/>
            <xs:field xpath="@refID"/>
        </xs:keyref>
    </xs:element>

</xs:schema>

=== TDave555/YIF399_XMLGyak/XMLTaskYIF399/DomParseYIF399/XMLYIF399.out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><filmtar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XMLSchemaYIF399.xsd">
	<rendezok>
		<rendezo RID="r01">
			<nev>David Zucker</nev>
			<eletkor>74</eletkor>
			<lakhely>
				<orszag>USA</orszag>
				<varos>Los Angeles</varos>
			</lakhely>
		</rendezo>
		<rendezo RID="r02">
			<nev>Peter Segal</nev>
			<eletkor>58</eletkor>
			<lakhely>
				<orszag>USA</orszag>
				<varos>Chicago</varos>
			</lakhely>
		</rendezo>
		<rendezo RID="r03">
			<nev>Keenen Ivory Wayans</nev>
			<eletkor>63</eletkor>
			<lakhely>
				<orszag>USA</orszag>
				<varos>New York</varos>
			</lakhely>
		</rendezo>
	</rendezok>
	<szineszek>
		<szinesz SzID="sz01">
			<nev>Leslie Nielsen</nev>
			<eletkor>50</eletkor>
			<lakhely>
				<orszag>USA</orszag>
				<varos>Fort Lauderdale</varos>
			</lakhely>
		</szinesz>
		<szinesz SzID="sz02">
			<nev>Priscilla Presley</nev>
			<eletkor>76</eletkor>
			<lakhely>
				<orszag>USA</orszag>
				<varos>Los Angeles</varos>
			</lakhely>
		</szinesz>
		<szinesz SzID="sz03">
			<nev>Marlon Wayans</nev>
			<eletkor>49</eletkor>
			<lakhely>
				<orszag>USA</orszag>
				<varos>Los Angeles</varos>
			</lakhely>
		</szinesz>
	</szineszek>
	<studiok>
		<studio SID="s01">
			<nev>Paramount Pictures</nev>
			<alapitas>1912</alapitas>
			<vezeto>Adolf Zukor</vezeto>
			<szekhely>
				<orszag>USA</orszag>
				<varos>Los Angeles</varos>
			</szekhely>
		</studio>
		<studio SID="s02">
			<nev>Miramax</nev>
			<alapitas>1979</alapitas>
			<vezeto>Bob Weinstein</vezeto>
			<szekhely>
				<orszag>USA</orszag>
				<varos>Santa Monica</varos>
			</szekhely>
		</studio>
	</studiok>
	<filmek>
		<film FID="f01">
			<cim>Csupasz pisztoly</cim>
			<bevetel>78756177</bevetel>
			<hossz>85</hossz>
			<megjelenes>
				<ev>1988</ev>
				<honap>12</honap>
				<nap>2</nap>
			</megjelenes>
			<RID refID="r01"/>
			<SID refID="s01"/>
		</film>
		<film FID="f02">
			<cim>Csupasz pisztoly 2</cim>
			<bevetel>192000000</bevetel>
			<hossz>81</hossz>
			<megjelenes>
				<ev>1991</ev>
				<honap>6</honap>
				<nap>28</nap>
			</megjelenes>
			<RID refID="r01"/>
			<SID refID="s01"/>
		</film>
		<film FID="f03">
			<cim>Csupasz pisztoly 3 – Az utolsó merénylet</cim>
			<bevetel>51132598</bevetel>
			<hossz>81</hossz>
			<megjelenes>
				<ev>1994</ev>
				<honap>3</honap>
				<nap>18</nap>
			</megjelenes>
			<RID refID="r02"/>
			<SID refID="s01"/>
		</film>
		<film FID="f04">
			<cim>Horrorra akadva 2</cim>
			<bevetel>71308997</bevetel>
			<hossz>83</hossz>
			<megjelenes>
				<ev>2001</ev>
				<honap>7</honap>
				<nap>4</nap>
			</megjelenes>
			<RID refID="r03"/>
			<SID refID="s02"/>
		</film>
	</filmek>
	<szereplesek>
		<szereples>
			<FID refID="f01"/>
			<SzID refID="sz01"/>
			<szerep>Frank Drebin hadnagy</szerep>
		</szereples>
		<szereples>
			<FID refID="f01"/>
			<SzID refID="sz02"/>
			<szerep>Jane Spencer</szerep>
		</szereples>
		<szereples>
			<FID refID="f02"/>
			<SzID refID="sz01"/>
			<szerep>Frank Drebin hadnagy</szerep>
		</szereples>
		<szereples>
			<FID refID="f02"/>
			<SzID refID="sz02"/>
			<szerep>Jane Spencer</szerep>
		</szereples>
		<szereples>
			<FID refID="f03"/>
			<SzID refID="sz01"/>
			<szerep>Frank Drebin hadnagy</szerep>
		</szereples>
		<szereples>
			<FID refID="f03"/>
			<SzID refID="sz02"/>
			<szerep>Jane Spencer</szerep>
		</szereples>
		<szereples>
			<FID refID="f04"/>
			<SzID refID="sz03"/>
			<szerep>Kurta Meeks</szerep>
		</szereples>
	</szereplesek>
</filmtar>
