=== TDave555/YIF399_XMLGyak/YIF399_1012/TDO_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Egyszerű típusok, korlátozások -->

    <xs:simpleType name="tolType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-1]?[0-9]|2[0-3]):[0-5][0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-1]?[0-9]|2[0-3]):[0-5][0-9]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="elmelet" />
            <xs:enumeration value="gyakorlat" />
        </xs:restriction>
    </xs:simpleType>
            
    <xs:simpleType name="idType">
        <xs:restriction base="xs:string">
            <xs:pattern value="ora_\d{2}" />
        </xs:restriction>
    </xs:simpleType>


    <!-- Egyszerű egyedek -->

    <xs:element name="targy" type="xs:string" />
    <xs:element name="nap" type="xs:string" />
    <xs:element name="tol" type="tolType" />
    <xs:element name="ig" type="igType" />
    <xs:element name="helyszin" type="xs:string" />
    <xs:element name="oktato" type="xs:string" />
    <xs:element name="szak" type="xs:string" />

    <!-- Attributumok -->

    <xs:attribute name="id" type="idType" />
    <xs:attribute name="tipus" type="tipusType" />


    <!-- Komplex egyedek -->

    <xs:element name="idopont">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nap" />
                <xs:element ref="tol" />
                <xs:element ref="ig" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="ora">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="targy" />
                <xs:element ref="idopont" />
                <xs:element ref="helyszin" />
                <xs:element ref="oktato" />
                <xs:element ref="szak" />
            </xs:sequence>
            <xs:attribute ref="id" /> 
            <xs:attribute ref="tipus" />
        </xs:complexType>
    </xs:element>


    <!-- Gyökér elem -->

    <xs:element name="toth_david_orarend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ora" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== TDave555/YIF399_XMLGyak/YIF399_1012/TDO_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<toth_david_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="TDO_orarend.xsd">
	<ora id="ora_01" tipus="elmelet">
		<targy>WEB technológiák 1</targy>
		<idopont>
			<nap>Hétfő</nap>
			<tol>08:00</tol>
			<ig>10:00</ig>
		</idopont>
		<helyszin>XXX. ea.</helyszin>
		<oktato>Agárdi Anita</oktato>
		<szak>Mérnökinformatikus - Korszerű WEB technológiák spec.</szak>
	</ora>
	<ora id="ora_02" tipus="elmelet">
		<targy>Korszerű információs technológiák</targy>
		<idopont>
			<nap>Hétfő</nap>
			<tol>14:00</tol>
			<ig>16:00</ig>
		</idopont>
		<helyszin>A1/320</helyszin>
		<oktato>Dr. Árvai László</oktato>
		<szak>Mérnökinformatikus</szak>
	</ora>
	<ora id="ora_03" tipus="elmelet">
		<targy>Integrált vállalati rendszerek</targy>
		<idopont>
			<nap>Hétfő</nap>
			<tol>16:00</tol>
			<ig>18:00</ig>
		</idopont>
		<helyszin>A1/313</helyszin>
		<oktato>Dr. Samad Dadvandipour</oktato>
		<szak>Mérnökinformatikus</szak>
	</ora>
	<ora id="ora_04" tipus="gyakorlat">
		<targy>WEB technológiák 1</targy>
		<idopont>
			<nap>Hétfő</nap>
			<tol>18:00</tol>
			<ig>20:00</ig>
		</idopont>
		<helyszin>Inf/103</helyszin>
		<oktato>Agárdi Anita</oktato>
		<szak>Mérnökinformatikus - Korszerű WEB technológiák spec.</szak>
	</ora>
	<ora id="ora_05" tipus="elmelet">
		<targy>Adatkezelés XML környezetben</targy>
		<idopont>
			<nap>Kedd</nap>
			<tol>12:00</tol>
			<ig>14:00</ig>
		</idopont>
		<helyszin>XXXII. ea.</helyszin>
		<oktato>Dr. Bednarik László</oktato>
		<szak>Mérnökinformatikus - Korszerű WEB technológiák spec.</szak>
	</ora>
	<ora id="ora_06" tipus="elmelet">
		<targy>Web-es alkalmazások (Java)</targy>
		<idopont>
			<nap>Szerda</nap>
			<tol>08:00</tol>
			<ig>10:00</ig>
		</idopont>
		<helyszin>Inf/103</helyszin>
		<oktato>Dr. Barabás Péter</oktato>
		<szak>Mérnökinformatikus - Korszerű WEB technológiák spec.</szak>
	</ora>
	<ora id="ora_07" tipus="gyakorlat">
		<targy>Adatkezelés XML környezetben</targy>
		<idopont>
			<nap>Szerda</nap>
			<tol>10:00</tol>
			<ig>12:00</ig>
		</idopont>
		<helyszin>Inf/101</helyszin>
		<oktato>Dr. Bednarik László</oktato>
		<szak>Mérnökinformatikus - Korszerű WEB technológiák spec.</szak>
	</ora>
	<ora id="ora_08" tipus="gyakorlat">
		<targy>Web-es alkalmazások (Java)</targy>
		<idopont>
			<nap>Szerda</nap>
			<tol>13:00</tol>
			<ig>15:00</ig>
		</idopont>
		<helyszin>Inf/202</helyszin>
		<oktato>Dr. Barabás Péter</oktato>
		<szak>Mérnökinformatikus - Korszerű WEB technológiák spec.</szak>
	</ora>
	<ora id="ora_09" tipus="gyakorlat">
		<targy>Integrált vállalati rendszerek</targy>
		<idopont>
			<nap>Szerda</nap>
			<tol>15:00</tol>
			<ig>17:00</ig>
		</idopont>
		<helyszin>Infó/15</helyszin>
		<oktato>Kulcsárné Dr. Forrai Mónika</oktato>
		<szak>Mérnökinformatikus</szak>
	</ora>
</toth_david_orarend>
