=== TDave555/YIF399_XMLGyak/YIF399_1012/XMLSchemaYIF399.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Egyszerű típusok, korlátozások -->

  <xs:simpleType name="csillagType">
    <xs:restriction base="xs:int">
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
      <xs:enumeration value="5" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="eletkorType">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="14" />
      <xs:maxInclusive value="100" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="osszegType">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{3,5} Ft"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <!-- Egyszerű egyedek -->

  <xs:element name="csillag" type="csillagType" />
  <xs:element name="varos" type="xs:string" />
  <xs:element name="utca" type="xs:string" />
  <xs:element name="hazszam" type="xs:string" />
  <xs:element name="nev" type="xs:string" />
  <xs:element name="eletkor" type="eletkorType" />
  <xs:element name="reszleg" type="xs:string" />
  <xs:element name="vegzettseg" type="xs:string" />
  <xs:element name="osszeg" type="osszegType" />
  <xs:element name="etel" type="xs:string" />
  <xs:element name="kezdete" type="xs:string" />
  <xs:element name="idotartama" type="xs:string" />
  <xs:element name="muszak" type="xs:string" />

  <!-- Attributumok -->

  <xs:attribute name="Ekod" type="xs:string" />
  <xs:attribute name="Fkod" type="xs:string" />
  <xs:attribute name="Gykod" type="xs:string" />
  <xs:attribute name="Szkod" type="xs:string" />
  <xs:attribute name="Vkod" type="xs:string" />

  <xs:attribute name="Eref" type="xs:string" />
  <xs:attribute name="Vref" type="xs:string" />

  <!-- Komplex egyedek -->

  <xs:element name="cim">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="varos" />
        <xs:element ref="utca" />
        <xs:element ref="hazszam" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gyakorlat">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kezdete" />
        <xs:element ref="idotartama" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="etterem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="csillag" minOccurs="1" maxOccurs="1" />
        <xs:element ref="cim" />
      </xs:sequence>
      <xs:attribute ref="Ekod" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="foszakacs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="eletkor" />
        <xs:element ref="vegzettseg" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="Fkod" use="required" />
      <xs:attribute ref="Eref" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="szakacs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="reszleg" />
        <xs:element ref="vegzettseg" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="Szkod" use="required" />
      <xs:attribute ref="Eref" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="gyakornok">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="gyakorlat" />
        <xs:element ref="muszak" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="Gykod" use="required" />
      <xs:attribute ref="Eref" />
    </xs:complexType>
  </xs:element>

  <xs:element name="vendeg">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
        <xs:element ref="eletkor" />
        <xs:element ref="cim" />
      </xs:sequence>
      <xs:attribute ref="Vkod" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="rendeles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="osszeg" />
        <xs:element ref="etel" />
      </xs:sequence>
      <xs:attribute ref="Eref" />
      <xs:attribute ref="Vref" />
    </xs:complexType>
  </xs:element>

  <!-- Gyökér elem -->

  <xs:element name="TDO_vendeglatas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="etterem" maxOccurs="unbounded" />
        <xs:element ref="foszakacs" maxOccurs="unbounded" />
        <xs:element ref="szakacs" maxOccurs="unbounded" />
        <xs:element ref="gyakornok" maxOccurs="unbounded" />
        <xs:element ref="vendeg" maxOccurs="unbounded" />
        <xs:element ref="rendeles" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
    
    <!-- xPath -->

    <xs:key name="etteremKey">
      <xs:selector xpath="etterem" />
      <xs:field xpath="@Ekod" />
    </xs:key>
    <xs:key name="foszakacsKey">
      <xs:selector xpath="foszakacs" />
      <xs:field xpath="@Fkod" />
    </xs:key>
    <xs:key name="szakacsKey">
      <xs:selector xpath="szakacs" />
      <xs:field xpath="@Szkod" />
    </xs:key>
    <xs:key name="gyakornokKey">
      <xs:selector xpath="gyakornok" />
      <xs:field xpath="@Gykod" />
    </xs:key>
    <xs:key name="vendegKey">
      <xs:selector xpath="vendeg" />
      <xs:field xpath="@Vkod" />
    </xs:key>

    <xs:keyref refer="etteremKey" name="RendelesEtteremForeignKey">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@Eref" />
    </xs:keyref>
    <xs:keyref refer="vendegKey" name="RendelesVendegForeignKey">
      <xs:selector xpath="rendeles" />
      <xs:field xpath="@Vref" />
    </xs:keyref>
    <xs:keyref refer="etteremKey" name="FoszakacsEtteremForeignKey">
      <xs:selector xpath="foszakacs" />
      <xs:field xpath="@Eref" />
    </xs:keyref>
    <xs:keyref refer="etteremKey" name="SzakacsEtteremForeignKey">
      <xs:selector xpath="szakacs" />
      <xs:field xpath="@Eref" />
    </xs:keyref>
    <xs:keyref refer="etteremKey" name="GyakornokEtteremForeignKey">
      <xs:selector xpath="gyakornok" />
      <xs:field xpath="@Eref" />
    </xs:keyref>
  </xs:element>
  
</xs:schema>

=== TDave555/YIF399_XMLGyak/YIF399_1012/XMLYIF399.xml
<?xml version="1.0" encoding="UTF-8"?>

<TDO_vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaYIF399.xsd" >

  <!-- éttermek -->

    <etterem Ekod="e1">
      <nev>Városi rántotthúsozó</nev>
      <csillag>2</csillag>
      <cim>
          <varos>Miskolc</varos>
            <utca>Széchenyi utca</utca>
            <hazszam>8</hazszam>
        </cim>
    </etterem>

    <etterem Ekod="e2">
        <nev>Finom falatok falodája</nev>
        <csillag>4</csillag>
        <cim>
            <varos>Kaposvár</varos>
            <utca>Vár utca</utca>
            <hazszam>35</hazszam>
        </cim>
    </etterem>

    <etterem Ekod="e3">
        <nev>Mariska néni házias konyhája</nev>
        <csillag>5</csillag>
        <cim>
            <varos>Eger</varos>
            <utca>Bornemissza utca</utca>
            <hazszam>22</hazszam>
        </cim>
    </etterem>


  <!-- főszakácsok -->

    <foszakacs Fkod="f1" Eref="e1">
        <nev>Álmos János</nev>
        <eletkor>42</eletkor>
        <vegzettseg>Masterclassegy By Gordon Ramsay</vegzettseg>
    </foszakacs>
  
    <foszakacs Fkod="f2" Eref="e2">
        <nev>Nagy Viktória</nev>
        <eletkor>35</eletkor>
        <vegzettseg>Gourmet szakács</vegzettseg>
        <vegzettseg>Barista</vegzettseg>
    </foszakacs>
  
    <foszakacs Fkod="f3" Eref="e3">
        <nev>Németh Árpád</nev>
        <eletkor>22</eletkor>
        <vegzettseg>Gasztronómiai menedzser</vegzettseg>
        <vegzettseg>Bar mixer</vegzettseg>
        <vegzettseg>OKJ Cukrász</vegzettseg>
    </foszakacs>
    

  <!-- szakácsok -->

    <szakacs Szkod="sz1" Eref="e1">
        <nev>Édes Anna</nev>
        <reszleg>Sütemény</reszleg>
        <vegzettseg>OKJ cukrász</vegzettseg>
        <vegzettseg>OKJ szakács</vegzettseg>
      </szakacs>

      <szakacs Szkod="sz2" Eref="e2">
        <nev>Tálas Elemér</nev>
        <reszleg>Sütő</reszleg>
        <vegzettseg>OKJ szakács</vegzettseg>
      </szakacs>

      <szakacs Szkod="sz3" Eref="e2">
        <nev>Kiss László</nev>
        <reszleg>Kóstoló</reszleg>
        <vegzettseg>Szomelié</vegzettseg>
        <vegzettseg>OKJ szakács</vegzettseg>
      </szakacs>

      <szakacs Szkod="sz4" Eref="e3">
        <nev>Babos Fanni</nev>
        <reszleg>Saláták</reszleg>
        <vegzettseg>OKJ szakács</vegzettseg>
      </szakacs>


  <!-- gyakornokok -->

    <gyakornok Gykod="gy1" Eref="e1">
      <nev>Tibi</nev>
      <gyakorlat>
        <kezdete>2022-06-24</kezdete>
        <idotartama>2 hónap</idotartama>
      </gyakorlat>
      <muszak>Délutáni</muszak>
    </gyakornok>

    <gyakornok Gykod="gy2" Eref="e2">
      <nev>Feri</nev>
      <gyakorlat>
        <kezdete>2021-12-01</kezdete>
        <idotartama>8 hónap</idotartama>
      </gyakorlat>
      <muszak>Esti</muszak>
      <muszak>Délutáni</muszak>
    </gyakornok>

    <gyakornok Gykod="gy3" Eref="e3">
      <nev>Laci</nev>
      <gyakorlat>
        <kezdete>2022-02-14</kezdete>
        <idotartama>6 hónap</idotartama>
      </gyakorlat>
      <muszak>Délelötti</muszak>
    </gyakornok>


  <!-- vendégek -->

    <vendeg Vkod="v1">
      <nev>Maros Árpád</nev>
      <eletkor>28</eletkor>
      <cim>
        <varos>Miskolc</varos>
        <utca>Blaha Lujza utca</utca>
        <hazszam>20</hazszam>
      </cim>
    </vendeg>
  
    <vendeg Vkod="v2">
      <nev>Lantos Ibolya</nev>
      <eletkor>33</eletkor>
      <cim>
        <varos>Kaposvár</varos>
        <utca>Arany utca</utca>
        <hazszam>99</hazszam>
      </cim>
    </vendeg>

    <vendeg Vkod="v3">
      <nev>Kovács István</nev>
      <eletkor>60</eletkor>
      <cim>
        <varos>Eger</varos>
        <utca>Hadak útja</utca>
        <hazszam>5</hazszam>
      </cim>
    </vendeg>


  <!-- rendelések -->

    <rendeles Eref="e1" Vref="v1">
      <osszeg>2600 Ft</osszeg>
      <etel>"2 szelett óriás rántott karaj + 1 adag sültkrumpli"</etel>
    </rendeles>
  
    <rendeles Eref="e2" Vref="v2">
      <osszeg>1200 Ft</osszeg>
      <etel>Csirkenuggets (12 db-os) + BBQ szósz + sültkrumpli</etel>
    </rendeles>
  
    <rendeles Eref="e3" Vref="v3">
      <osszeg>1500 Ft</osszeg>
      <etel>Bajai halászlé + 2 szelet kenyér</etel>
    </rendeles>


</TDO_vendeglatas>
