=== TDave555/YIF399_XMLGyak/YIF399_0928/TDO_ertodtd.dtd
<!ATTLIST TDOmodell xmlns:a CDATA #REQUIRED
  xmlns:b CDATA #REQUIRED
  xmlns:c CDATA #REQUIRED
  xmlns:a_b CDATA #REQUIRED>
<!ELEMENT TDOmodell (A+, C+, B+, A_B+)>

<!ELEMENT A (a:b+, a:c)>
<!ATTLIST A a ID #REQUIRED>
<!ELEMENT a:b (a:x, a:y)>
<!ELEMENT a:x (#PCDATA)>
<!ELEMENT a:y (#PCDATA)>
<!ELEMENT a:c (a:d, a:e)>
<!ELEMENT a:d (#PCDATA)>
<!ELEMENT a:e (#PCDATA)>

<!ELEMENT C (c:b)>
<!ATTLIST C a ID #REQUIRED>
<!ELEMENT c:b (#PCDATA)>

<!ELEMENT B (b:b)>
<!ATTLIST B a ID #REQUIRED
  CREF IDREF #REQUIRED>
<!ELEMENT b:b (b:x, b:y)>
<!ELEMENT b:x (#PCDATA)>
<!ELEMENT b:y (#PCDATA)>

<!ELEMENT A_B (a_b:c)>
<!ATTLIST A_B AREF IDREF #REQUIRED
  BREF IDREF #REQUIRED>
<!ELEMENT a_b:c (#PCDATA)>

=== TDave555/YIF399_XMLGyak/YIF399_0928/TDO_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TDOmodell SYSTEM "TDO_ertodtd.dtd">
<TDOmodell xmlns:a="./namespaces/a.txt" xmlns:b="./namespaces/b.txt" 
xmlns:c="./namespaces/c.txt" xmlns:a_b="./namespaces/a_b.txt">

    <A a="a01">
        <a:b>
            <a:x>asd</a:x>
            <a:y>asd</a:y>
        </a:b>
        <a:c>
            <a:d>asd</a:d>
            <a:e>asd</a:e>
        </a:c>
    </A>
    <A a="a02">
        <a:b>
            <a:x>asd</a:x>
            <a:y>asd</a:y>
        </a:b>
        <a:c>
            <a:d>asd</a:d>
            <a:e>asd</a:e>
        </a:c>
    </A>

    <C a="c01">
        <c:b>asd</c:b>
    </C>

    <B a="b01" CREF="c01">
        <b:b>
            <b:x>asd</b:x>
            <b:y>asd</b:y>
        </b:b>
    </B>
    <B a="b02" CREF="c01">
        <b:b>
            <b:x>asd</b:x>
            <b:y>asd</b:y>
        </b:b>
    </B>

    <A_B AREF="a01" BREF="b01">
        <a_b:c>A1+B1</a_b:c>
    </A_B>
    <A_B AREF="a02" BREF="b02">
        <a_b:c>A2+B2</a_b:c>
    </A_B>
    <A_B AREF="a01" BREF="b02">
        <a_b:c>A1+B2</a_b:c>
    </A_B>
    <A_B AREF="a02" BREF="b01">
        <a_b:c>A2+B1</a_b:c>
    </A_B>

</TDOmodell>
